"""
Data models for the Self-Healing System.
Defines structures for logs, errors, fixes, and reports.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pathlib import Path


class LogLevel(Enum):
    """Log level enumeration"""
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ErrorSeverity(Enum):
    """Error severity classification"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class FixStatus(Enum):
    """Status of a fix proposal"""
    PENDING = "pending"
    TESTING = "testing"
    PASSED = "passed"
    FAILED = "failed"
    APPLIED = "applied"
    REJECTED = "rejected"


@dataclass
class LogEntry:
    """Represents a single log entry from the monitored service"""
    timestamp: datetime
    level: LogLevel
    message: str
    source_file: Optional[str] = None
    line_number: Optional[int] = None
    stack_trace: Optional[str] = None
    raw_line: str = ""
    
    @classmethod
    def from_raw(cls, raw_line: str) -> Optional["LogEntry"]:
        """Parse a raw log line into a LogEntry object"""
        try:
            # Expected format: [TIMESTAMP] [LEVEL] MESSAGE
            # Or Node.js format: Error: message\n    at file:line
            parts = raw_line.strip()
            if not parts:
                return None
            
            # Detect log level
            level = LogLevel.INFO
            for lvl in LogLevel:
                if lvl.value in parts.upper():
                    level = lvl
                    break
            
            # Check for error indicators
            if "Error:" in parts or "error:" in parts:
                level = LogLevel.ERROR
            elif "Warning:" in parts or "warning:" in parts:
                level = LogLevel.WARNING
            
            return cls(
                timestamp=datetime.now(),
                level=level,
                message=parts,
                raw_line=raw_line,
            )
        except Exception:
            return None
    
    @property
    def is_error(self) -> bool:
        """Check if this log entry represents an error"""
        return self.level in (LogLevel.ERROR, LogLevel.CRITICAL)
    
    @property
    def is_warning(self) -> bool:
        """Check if this log entry represents a warning"""
        return self.level == LogLevel.WARNING


@dataclass
class ErrorInfo:
    """Detailed information about a detected error"""
    error_type: str
    message: str
    stack_trace: str
    source_file: str
    line_number: int
    severity: ErrorSeverity
    timestamp: datetime = field(default_factory=datetime.now)
    context_before: List[str] = field(default_factory=list)
    context_after: List[str] = field(default_factory=list)
    related_files: List[str] = field(default_factory=list)
    root_cause_analysis: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "error_type": self.error_type,
            "message": self.message,
            "stack_trace": self.stack_trace,
            "source_file": self.source_file,
            "line_number": self.line_number,
            "severity": self.severity.value,
            "timestamp": self.timestamp.isoformat(),
            "context_before": self.context_before,
            "context_after": self.context_after,
            "related_files": self.related_files,
            "root_cause_analysis": self.root_cause_analysis,
        }


@dataclass
class FixProposal:
    """A proposed fix generated by the AI agent"""
    fix_id: str
    target_file: str
    original_code: str
    fixed_code: str
    explanation: str
    confidence_score: float
    status: FixStatus = FixStatus.PENDING
    attempt_number: int = 1
    timestamp: datetime = field(default_factory=datetime.now)
    diff: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "fix_id": self.fix_id,
            "target_file": self.target_file,
            "original_code": self.original_code,
            "fixed_code": self.fixed_code,
            "explanation": self.explanation,
            "confidence_score": self.confidence_score,
            "status": self.status.value,
            "attempt_number": self.attempt_number,
            "timestamp": self.timestamp.isoformat(),
            "diff": self.diff,
        }


@dataclass
class TestResult:
    """Result of running tests on a fix"""
    fix_id: str
    passed: bool
    total_tests: int
    passed_tests: int
    failed_tests: int
    test_output: str
    execution_time: float  # seconds
    timestamp: datetime = field(default_factory=datetime.now)
    error_messages: List[str] = field(default_factory=list)
    
    @property
    def pass_rate(self) -> float:
        """Calculate test pass rate"""
        if self.total_tests == 0:
            return 0.0
        return self.passed_tests / self.total_tests * 100
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "fix_id": self.fix_id,
            "passed": self.passed,
            "total_tests": self.total_tests,
            "passed_tests": self.passed_tests,
            "failed_tests": self.failed_tests,
            "test_output": self.test_output,
            "execution_time": self.execution_time,
            "timestamp": self.timestamp.isoformat(),
            "error_messages": self.error_messages,
            "pass_rate": self.pass_rate,
        }


@dataclass
class HealingReport:
    """Complete report of a healing operation"""
    report_id: str
    error_info: ErrorInfo
    fix_proposals: List[FixProposal]
    test_results: List[TestResult]
    final_fix: Optional[FixProposal]
    git_branch: Optional[str]
    git_commit: Optional[str]
    status: str  # "success", "failed", "pending_approval"
    total_attempts: int
    timestamp: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "report_id": self.report_id,
            "error_info": self.error_info.to_dict(),
            "fix_proposals": [fp.to_dict() for fp in self.fix_proposals],
            "test_results": [tr.to_dict() for tr in self.test_results],
            "final_fix": self.final_fix.to_dict() if self.final_fix else None,
            "git_branch": self.git_branch,
            "git_commit": self.git_commit,
            "status": self.status,
            "total_attempts": self.total_attempts,
            "timestamp": self.timestamp.isoformat(),
        }
    
    def summary(self) -> str:
        """Generate a human-readable summary"""
        return f"""
═══════════════════════════════════════════════════════════════
                    SELF-HEALING REPORT
═══════════════════════════════════════════════════════════════
Report ID: {self.report_id}
Timestamp: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}
Status: {self.status.upper()}

ERROR DETAILS:
  Type: {self.error_info.error_type}
  File: {self.error_info.source_file}:{self.error_info.line_number}
  Severity: {self.error_info.severity.value}
  Message: {self.error_info.message}

FIX SUMMARY:
  Total Attempts: {self.total_attempts}
  Final Status: {'✓ FIXED' if self.final_fix else '✗ NOT FIXED'}
  
GIT INFORMATION:
  Branch: {self.git_branch or 'N/A'}
  Commit: {self.git_commit or 'N/A'}

TEST RESULTS:
  Passed: {sum(1 for tr in self.test_results if tr.passed)}
  Failed: {sum(1 for tr in self.test_results if not tr.passed)}
═══════════════════════════════════════════════════════════════
"""
