"""
Git Handler Subprocess (subprocess4)
Manages git operations for fix branches.
"""

import asyncio
import uuid
from pathlib import Path
from typing import Tuple, Optional
from datetime import datetime
import subprocess

from utils.logger import setup_colored_logger
from utils.models import FixProposal, ErrorInfo

logger = setup_colored_logger("git_handler")


class GitHandler:
    """
    Handles Git operations for creating fix branches.
    
    subprocess4 -> 
        git branching (tested code)
        email(proposed fix (git link), generated test results, severity)
    """
    
    def __init__(
        self, 
        repo_path: Path,
        branch_prefix: str = "ai-fix",
        remote_name: str = "origin"
    ):
        self.repo_path = repo_path
        self.branch_prefix = branch_prefix
        self.remote_name = remote_name
        
    async def create_fix_branch(
        self, 
        fix: FixProposal, 
        error_info: ErrorInfo
    ) -> Tuple[str, str]:
        """
        Create a new git branch with the fix applied.
        
        Args:
            fix: The fix proposal to apply
            error_info: Information about the error being fixed
            
        Returns:
            Tuple of (branch_name, commit_hash)
        """
        # Generate unique branch name
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        short_id = fix.fix_id[:8]
        branch_name = f"{self.branch_prefix}/{error_info.error_type.lower()}-{timestamp}-{short_id}"
        
        logger.info(f"Creating fix branch: {branch_name}")
        
        try:
            # Get current branch
            original_branch = await self._run_git_command("rev-parse", "--abbrev-ref", "HEAD")
            original_branch = original_branch.strip()
            
            # Create and checkout new branch
            await self._run_git_command("checkout", "-b", branch_name)
            
            # Apply the fix
            await self._apply_fix(fix)
            
            # Stage changes
            await self._run_git_command("add", "-A")
            
            # Create commit message
            commit_message = self._create_commit_message(fix, error_info)
            
            # Commit changes
            await self._run_git_command("commit", "-m", commit_message)
            
            # Get commit hash
            commit_hash = await self._run_git_command("rev-parse", "HEAD")
            commit_hash = commit_hash.strip()
            
            logger.info(f"✓ Fix committed: {commit_hash[:8]}")
            
            # Return to original branch
            await self._run_git_command("checkout", original_branch)
            
            return branch_name, commit_hash
            
        except Exception as e:
            logger.error(f"Error creating fix branch: {e}")
            # Try to return to original branch on error
            try:
                await self._run_git_command("checkout", original_branch)
            except:
                pass
            raise
    
    async def _apply_fix(self, fix: FixProposal):
        """Apply fix to the target file"""
        target_file = Path(fix.target_file)
        
        if not target_file.is_absolute():
            target_file = self.repo_path / target_file
        
        logger.info(f"Applying fix to: {target_file}")
        
        # Write the fixed code
        with open(target_file, 'w', encoding='utf-8') as f:
            f.write(fix.fixed_code)
    
    def _create_commit_message(self, fix: FixProposal, error_info: ErrorInfo) -> str:
        """Create a descriptive commit message"""
        return f"""fix({error_info.error_type}): AI-generated fix for {Path(fix.target_file).name}

Error: {error_info.message[:100]}
Severity: {error_info.severity.value}
Fix ID: {fix.fix_id}
Confidence: {fix.confidence_score:.2f}

{fix.explanation}

---
This fix was automatically generated by the Self-Healing System.
Attempt #{fix.attempt_number}
"""
    
    async def _run_git_command(self, *args) -> str:
        """Run a git command and return output"""
        cmd = ["git", *args]
        
        process = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=str(self.repo_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        
        stdout, stderr = await process.communicate()
        
        if process.returncode != 0:
            error_msg = stderr.decode('utf-8', errors='replace')
            raise Exception(f"Git command failed: {error_msg}")
        
        return stdout.decode('utf-8', errors='replace')
    
    async def get_repo_url(self) -> Optional[str]:
        """Get the remote repository URL"""
        try:
            url = await self._run_git_command("remote", "get-url", self.remote_name)
            return url.strip()
        except:
            return None
    
    async def get_branch_url(self, branch_name: str) -> Optional[str]:
        """Generate a URL to view the branch on GitHub/GitLab"""
        repo_url = await self.get_repo_url()
        if not repo_url:
            return None
        
        # Convert SSH URL to HTTPS if needed
        if repo_url.startswith("git@"):
            # git@github.com:user/repo.git -> https://github.com/user/repo
            repo_url = repo_url.replace("git@", "https://")
            repo_url = repo_url.replace(":", "/", 1)
        
        # Remove .git suffix
        if repo_url.endswith(".git"):
            repo_url = repo_url[:-4]
        
        # Generate branch URL
        if "github.com" in repo_url:
            return f"{repo_url}/tree/{branch_name}"
        elif "gitlab" in repo_url:
            return f"{repo_url}/-/tree/{branch_name}"
        else:
            return f"{repo_url}/tree/{branch_name}"
    
    async def get_diff(self, branch_name: str) -> str:
        """Get the diff for a branch compared to main"""
        try:
            diff = await self._run_git_command("diff", "main...", branch_name)
            return diff
        except:
            return ""
    
    async def push_branch(self, branch_name: str) -> bool:
        """Push branch to remote"""
        try:
            await self._run_git_command("push", "-u", self.remote_name, branch_name)
            logger.info(f"✓ Branch pushed to remote: {branch_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to push branch: {e}")
            return False
    
    async def create_pull_request_info(
        self, 
        branch_name: str, 
        fix: FixProposal, 
        error_info: ErrorInfo
    ) -> dict:
        """Generate information for creating a PR/MR"""
        return {
            "title": f"fix({error_info.error_type}): {error_info.message[:50]}",
            "body": f"""## AI-Generated Fix

### Error Details
- **Type**: {error_info.error_type}
- **Severity**: {error_info.severity.value}
- **File**: {error_info.source_file}:{error_info.line_number}
- **Message**: {error_info.message}

### Fix Details
- **Fix ID**: {fix.fix_id}
- **Confidence Score**: {fix.confidence_score:.2%}
- **Attempt Number**: {fix.attempt_number}

### Explanation
{fix.explanation}

### Root Cause Analysis
{error_info.root_cause_analysis}

---
*This PR was automatically generated by the Self-Healing System.*
""",
            "source_branch": branch_name,
            "target_branch": "main",
        }
